### ISSUE TITLE
Stakeholder Matrix

### ISSUE THREAD

**Issue by AbrafoJ** [AbrafoJ/LACleanUPSites#4] opened 2019-01-30 23:36 UTC

**Comment by DiegoG2212** [comment] 2019-02-01 20:53
Board of Directors: Matt and his management team came with the idea of LA clean up site application and main users of that application. They are actively using the information provided by the app so they can make new investments in different lands with environmental hazards to buy around Los Angeles.

Third-Party: Lawyer/Attorney and or insurance agent are passive users of the application as they don’t really care the information given in the app, but they care more about the transaction in between the board of directors and the owners of the property.

Suppliers or Investors: Any person willing to help the development team with any financial, technological or any other kind of resource support with this application. 

Government: will be indirectly benefited from this app as there will be less hazardous lands that they would have to worry about which ends in less money spend in this type problems.

Local/global communities: Any Local or global community will be indirectly impacted by our app as their life quality will be improved when different hazardous areas are cleaned.

Customers: are the people who uses our application and are constantly using the service provided by the application. For example: The board of directors, any other company who has a similar business like them or anyone interested in any type of information provided by our app.  

Employees: are the different developers the LA clean up site application has. They are the people who makes the application work as intended and possibly maintain it. 

The property owners (of the hazardous areas only and are selling): will indirectly benefit by our app as they will not have much trouble to look for a customer to sell their property too even though their property has been badly affected by any hazard in their area.   

Neighbors of the hazardous area that are on sale: will be indirectly benefited by our app because the zone will eventually be clean up and improve their quality of life.

Companies who have the information needed for our app: will be directly benefited by our app as it will bring some money to their company or partnership with our app for the use of their databases to make our app work.

**Closed** 2019-02-04 01:16 UTC
